name: Run Speedlify Tests

on:
  workflow_dispatch:
  schedule:
    - cron: '10 13 * * *'

    
    
jobs:
  build:
    name: Trigger Site Rebuild
    runs-on: ubuntu-latest
    steps:
      - name: Echo
        # Hit the webhook endpoint to rebuild  from the "main" branch
        run: echo "hello world"
