name: Run Speedlify Tests

on:
  workflow_dispatch:
  schedule:
    - cron: '10 13 * * *'

    
    
jobs:
  build:
    name: Install Pacakages
    runs-on: ubuntu-latest
    steps:
      - name: Yarn Install
        # Hit the webhook endpoint to rebuild  from the "main" branch
        run: yarn
