name: Run Speedlify Tests

on:
  workflow_dispatch:
  schedule:
    - cron: '10 13 * * *'

jobs:
  build:
    name: Install and Test Sites
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install Packages
        run: yarn
      - name: Test Pages
        run: yarn test-pages
      - name: Configure Git
        run: |
          git config user.name "GitHub Actions Bot"
          git config user.email "<>"
      - name: Git Commit
        run: "git commit -m -a --allow-empty `chore: run page tests - date +'%Y/%m/%d'`"
      - name: Push Changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}
